[register]
output_path = "../../data/mimir/register.csv"

[register.parse]
drop_non_pro_players = true

[register.parse.columns]
to_int64 = [
    "birth_year",
    "birth_month",
    "birth_day",
    "death_year",
    "death_month",
    "death_day",
    "pro_played_first",
    "pro_played_last",
    "mlb_played_first",
    "mlb_played_last",
    "col_played_first",
    "col_played_last"
]
to_int_then_string = [
    "key_mlbam",
    "key_fangraphs"
]
string_key = [
    "key_retro",
    "key_bbref",
    "key_bbref_minors"
]
discard = [
    "key_npb",
    "key_sr_nfl",
    "key_sr_nhl",
    "key_sr_nba",
    "key_findagrave",
    "pro_managed_first",
    "pro_managed_last",
    "mlb_managed_first",
    "mlb_managed_last",
    "col_managed_first",
    "col_managed_last",
    "pro_umpired_first",
    "pro_umpired_last",
    "mlb_umpired_first",
    "mlb_umpired_last"
]


[register.parse.columns.rename]
key_retro = "retro_id"
key_bbref = "bbref_id"
key_bbref_minors = "bbref_minors_id"
key_mlbam = "mlb_id"
key_fangraphs = "fangraphs_id"
key_uuid = "register_uuid"
key_person = "register_id"
